name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  run-linter:
    name: Lint + Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: v22.2.0
      - name: Install dependencies
        run: npm install --frozen-lockfile
      - name: Run linter + prettier
        run: npm run lint:ci

  run-tests:
    name: Test
    # needs: run-linter
    runs-on: ubuntu-latest
    services:
      mariadb-test:
        image: mariadb:10.6.18
        env:
          MARIADB_USER: user
          MARIADB_PASSWORD: password
          MARIADB_DATABASE: ordinary_helper_test_database
          MARIADB_ROOT_PASSWORD: password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --host=127.0.0.1 --user=root --password=password" --health-interval=5s --health-timeout=3s --health-retries=5
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: v22.2.0
      - name: Install dependencies
        run: npm install --frozen-lockfile
      - name: Wait for Database to Start
        run: npx wait-on tcp:3306
      - name: output containers
        run: docker ps
      - name: Check MariaDB logs
        run: docker logs $(docker ps -q --filter "name=mariadb-test")
      - name: Install MySQL client
        run: sudo apt-get install mysql-client
      - name: Test DB connection
        run: mysql -h 127.0.0.1 -u user -ppassword -e "SHOW DATABASES;"
      - name: Run tests
        env:
          DB_TEST_NAME: ordinary_helper_test_database
          DB_TEST_USER: user
          DB_TEST_PASSWORD: password
          DB_TEST_HOST: 127.0.0.1
        run: npm run test
